version: "3.1"
services:
  nginx:
    image: nginx:alpine
    build: 
      context: "./nginx"
    ports: 
    -  "8080:80"    
    volumes:
    - ./nginx/config:/etc/nginx/conf.d/
  php:
    image: php-fpm:7.2-alpine
    build:  
      context: "./php-fpm"
    ports: 
    -  "9000:9000"
    volumes:
    - ../src:/var/www
    - ./php-fpm/config:/usr/local/etc/php-fpm
  db:
    image: mysql:5.7
    ports: 
    -  "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=dockerdb
      - MYSQL_USER=andrew
      - MYSQL_ROOT_PASSWORD=assword

